repos:
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
  - id: interrogate
    args: [--fail-under=80, --verbose]
#- repo: local
#  hooks:
#  - id: wily
#    name: wily
#    entry: wily diff
#    verbose: true
#    language: python
#    additional_dependencies: [wily]
